# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
#cache:
#  packages: true
repos:
  CRAN: https://cloud.r-project.org

# managing node in a project for another language
# https://austinpray.com/ops/2015/09/20/change-travis-node-version.html
install:
  - echo "***node***"
  - node --version
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8
  - npm install
  - echo "***node***"
  - node --version

matrix:
  include:
  - r: devel
  - r: release
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel

addons:
  apt:
    packages:
      - libv8-dev       # for V8
      - valgrind        # for V8
      - libmagick++-dev # magick
